### ISSUE TITLE
Input simulation

### ISSUE THREAD

**Issue by KarakLive** [SaqibS/VirtualInput#1]
I wrote Windows keyboard and mouse simulation code, and was looking for a home for it.  This looks like a better place than starting my own project  :)  I am new to github (usually use codeplex) and can't seem to find any useful communication features, but I assume they're in here somewhere...?  Hopefully something better than opening an Issue for this?  Hopefully you notice this?  Anyway LMK, if I get this code integrated in the next few days, would it be likely to get pulled into main in a few days after?

**Comment by SaqibS** [comment]
Hi, thanks for the message (I couldn't find a private messaging feature either)

I'd certainly be interested to look at your contribution and if/when appropriate integrate it into the main branch. If it all looked good this could be very quickly.

Assuming you haven't used Github before, I'd recommend:
- From the web UI, fork the repository
- Clone karakLive/VirtualInput
- Commit and push to your fork
- Send a pull request and I'll take a look

If you want to discuss further, email string.Format("{0}@{1}{2}.com", "me", "saqib", "shaikh");

**Comment by KarakLive** [comment]
Ugh, git is so involved.  (First time using.)  I did a "commit" but i think that's just to a local DB on my machine.  At least, viewing the code at https://github.com/KarakLive/VirtualInput does not show the new files.  When I try to push the code... I dont understand what to target a push to, I thought it would be like:

Pushing to git://github.com/KarakLive/VirtualInput.git
fatal: remote error: 
  You can't push to git://github.com/KarakLive/VirtualInput.git
  Use git@github.com:KarakLive/VirtualInput.git

Pushing to git@github.com:KarakLive/VirtualInput.git
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

So what the heck, I try:

Pushing to git://github.com/SaqibS/VirtualInput.git
fatal: remote error: 
  You can't push to git://github.com/SaqibS/VirtualInput.git
  Use git@github.com:SaqibS/VirtualInput.git

... when trying to set git@github.com:SaqibS/VirtualInput.git I still get a cryptic message which I assume means I just don't have permission to push to it (which is expected just the message isn't very helpful):
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

Anyway, I'll give it another go eventually when I have some time again.

**Comment by KarakLive** [comment]
Not sure if it automatically messaged you, but the initial pull request has been in for a while.
